name: Helm Charts
on:
  push:
    branches:
      - feature
      - develop
      - master
  pull_request:
    branches:
      - feature
      - develop
      - master
    

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install helm and plugins
        run: chmod +x ./scripts/install.sh && ./scripts/install.sh
      - name: Release charts
        run: chmod +x ./scripts/release.sh && ./scripts/release.sh
        env:
          HELM_SERVICE_ACCOUNT_KEY: ${{ secrets.HELM_SERVICE_ACCOUNT_KEY }}
          
